### ISSUE TITLE
Abort happens with single core/processor systems

### ISSUE THREAD

**Issue by mike-myers-tob** [trailofbits/ebpfpub#54]
A user writes...

> While trying to test in KVM images

> $ cat /sys/devices/system/cpu/possible
> 0
> $ nproc
> 1
>
> I have another KVM setup with two processors and the file looks like this:
>
> $ cat /sys/devices/system/cpu/possible
> 0-1
> $ nproc
> 2

> What I found out was a VM with only 1 processor defined will not pass this formatting check

```cpp
auto separator = cpu_info.find('-');
  if (separator == std::string::npos) {
    throw std::runtime_error(
        "Failed to find the range separator in the following file: " +
        kPossibleCpuPseudoFile);
  }
```

Partial stack trace:

```
Thread 5 "procwall" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff6429700 (LWP 21251)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7c57859 in __GI_abort () at abort.c:79
#2  0x0000000000627534 in abort_message ()
#3  0x0000000000627656 in demangling_terminate_handler() ()
#4  0x0000000000626187 in std::__terminate(void (*)()) ()
#5  0x0000000000626338 in __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) ()
#6  0x0000000000626307 in __cxa_throw ()
#7  0x00000000007f7d51 in tob::ebpf::getPossibleProcessorCount() ()
#8  0x00000000007d0fe3 in tob::ebpfpub::BufferStorage::getBuffer(std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >&, unsigned long) ()
#9  0x00000000007d331c in tob::ebpfpub::FunctionTracer::parseEventData(tob::ebpfpub::BufferReader&, unsigned int, unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<tob::ebpfpub::IFunctionTracer::Parameter, std::__1::allocator<tob::ebpfpub::IFunctionTracer::Parameter> > const&, std::__1::vector<tob::ebpfpub::FunctionTracer::ParameterListIndexEntry, std::__1::allocator<tob::ebpfpub::FunctionTracer::ParameterListIndexEntry> > const&, tob::ebpfpub::IBufferStorage&) ()
#10 0x00000000007d277b in tob::ebpfpub::FunctionTracer::parseEventData(tob::ebpfpub::BufferReader&) const ()
#11 0x00000000007cf94d in tob::ebpfpub::PerfEventReader::exec(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1l> > const&, std::__1::function<void (std::__1::vector<tob::ebpfpub::IFunctionTracer::Event, std::__1::allocator<tob::ebpfpub::IFunctionTracer::Event> > const&, tob::ebpfpub::IPerfEventReader::ErrorCounters const&)>) ()
```

**Comment by alessandrogario** [comment]
Fixed in commit 84f8a1eec39cf6c1fd218de49b0d595c2be58a31
